config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings
    get 'home/index'
    get 'bookings/index'
    
    root 'pages#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    
    validates :name, :number_of_people, :start_time, :end_time, presence: true # Required fields
    validates :end_time, comparison: { greater_than: :start_time }
    validates :start_time, comparison: { greater_than: Date.today }

    validate :validate_other_booking_overlap

    def period
      start_time..end_time
    end
  
    private
    def validate_other_booking_overlap
      other_bookings = Booking.all
      is_overlapping = other_bookings.any? do |other_booking|
        period.overlaps?(other_booking.period)
      end
      errors.add(:Booked!, 'Those dates are already booked, please check the calendar') if is_overlapping
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :bookings

  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        stored_location_for(resource) || bookings_path
      end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:update, :edit, :destroy] unless :check_admin

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = current_user.bookings.build
    
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @booking = current_user.bookings.find_by(id: params[:id])
    redirect_to bookings_path, notice: "Not Authorized To Edit This Booking" if @booking.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:name, :number_of_people, :start_time, :end_time, :user_id)
    end
    def check_admin
      current_user.admin?    
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
<% if current_user.admin? %>
<tr>
    <td><%= booking.name %></td>
    <td><%= booking.number_of_people %></td>
    <td><%= booking.start_time.strftime("%d/%m/%Y") %></td>
    <td><%= booking.end_time.strftime("%d/%m/%Y") %></td>
    <td><%= booking.id %></td>
    
    <td>
    <%= link_to 'Edit', edit_booking_path(booking), class:"button is-small is-responsive" %>   
    <%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-small is-responsive is-danger" %>
    </td>
  </tr>
<% elsif booking.user == current_user %>    
<tr>
    <td><%= booking.name %></td>
    <td><%= booking.number_of_people %></td>
    <td><%= booking.start_time.strftime("%d/%m/%Y") %></td>
    <td><%= booking.end_time.strftime("%d/%m/%Y") %></td>
    <td><%= booking.id %></td>
    
    <td>
    <%= link_to 'Edit', edit_booking_path(booking), class:"button is-small is-responsive" %>
    <%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-small is-responsive is-danger" %>
    </td>
  </tr>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div class="notification is-danger is-light">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul></div>
      <div style="color: red">
    </div>
  <% end %>
  <br />
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number_of_people, style: "display: block" %>
    <%= form.number_field :number_of_people %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.date_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.date_field :end_time %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :booking_user_id, value:current_user.id, type: :hidden %>
  </div>
  <br />  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<h1>Calendar</h1><box class="box">Bookings </box>
<%= month_calendar events: @bookings do |date, bookings| %>  
  <%= date.to_formatted_s(:short) %>  
  <% bookings.each do |booking| %>  
    <div>
      <% if current_user.admin? %>
      <%= booking.name %>
      <% elsif booking.user == current_user %>  
      <%= booking.name %>
      <% end %>  
    </div>  
  <% end %>
<% end %>
<br />
<h1>Bookings</h1>
<div id="bookings">
  <table class="table is-bordered" -row-even-hover-background-color>
  <thead class="table">
    <tr>
      <th>Booking Name</th>
      <th>Number Of People</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Booking ID</th>
      
      <th col-span="3"</th>
    </tr>
  </thead>
    <% @bookings = Booking.all
    @bookings = @bookings.sort_by {|booking| booking.start_time}
    @bookings.each do |booking| %>
    <%= render booking %>
  <% end %>
  </table>  
</div>
<br />
<button class="button is-primary"><%= link_to "Add New booking", new_booking_path %></button>

app/views/bookings/new.html.erb
<div class="card">
  <div class="card-content">
    <div class="content">
    <header class="card-header">
      <h1>New booking</h1>
      </header>
<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/layouts/_alerts.html.erb
<div class="notification is-warning">
  <button class="delete"></button>
  <%= notice %>
</div>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>

app/views/layouts/_header.html.erb
<nav class="navbar" is-spaced role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
      <a class="navbar-item" href="#">
        <% if current_user %>
        <%= current_user.email %>
        <% if current_user.admin? %>
        <p> - admin<p/>
        <% end %>
        <% end %>            
      </a>
      <div class="navbar-burger burger" data-target="main-nav">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="main-nav" class="navbar-menu">
      <div class="navbar-start">
        <%= link_to root_url, class: 'navbar-item' do %>
          <span class="icon"><i class="far fa-gem"></i></span>
          <span>Home</span>
        <% end %>

        <% if current_user %>
          <%= link_to bookings_url, class: 'navbar-item' do %>
          <span class="icon"><i class="far fa-star"></i></span>
          <span>Bookings</span>
          <% end %>

          <%= link_to destroy_user_session_path, class: 'navbar-item' do %>
          <span class="icon"><i class="far fa-star"></i></span>
          <span>Sign Out</span>
          <% end %>

        <% else %>
          <%= link_to new_user_registration_path, class: 'navbar-item' do %>
          <span class="icon"><i class="far fa-star"></i></span>
          <span>Sign Up</span>
          <% end %>

          <%= link_to new_user_session_path, class: 'navbar-item' do %>
          <span class="icon"><i class="far fa-star"></i></span>
          <span>Login</span>
          <% end %>
    <% end %>    
      </div>
    </div>
  </nav>  
</div>
<script type="text/javascript"> <!-- add this for menu toggle button  -->
(function() {
    var burger = document.querySelector('.navbar-burger');
    var menu = document.querySelector('#'+burger.dataset.target);
    burger.addEventListener('click', function() {
        burger.classList.toggle('is-active');
        menu.classList.toggle('is-active');
    });
})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/sandstone/bulmaswatch.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>  
  <p class="alert"><%= alert %></p>
  <%= render "layouts/header" %>
  <section class="section">
    <div class="content">
      <%= yield %>
    </div>
  </section>
</body>
</html>

app/views/pages/home.html.erb
<%= link_to new_user_session_path do %>
<button class="button is-large">Login</button>
<% end %>

<%= link_to new_user_registration_path do %>
<button class="button is-large">Sign Up</button>
<% end %>